channels:
- conda-forge
dependencies:
- coveralls
- coverage
- bidict =0.22.1
- cloudpickle =3.0.0
- graphviz =8.1.0
- matplotlib =3.8.0
- pyiron_base =0.6.8
- python-graphviz =0.20.1
- toposort =1.10
- typeguard =4.1.5
- lammps
- pyiron_atomistics =0.3.5
- pyiron-data =0.0.24
- numpy =1.26.0
