channels:
- conda-forge
dependencies:
- ipykernel
- nbsphinx
- coveralls
- coverage
- bidict =0.22.1
- cloudpickle =3.0.0
- graphviz =8.1.0
- maggma =0.57.4
- matplotlib =3.8.0
- numpy =1.26.0
- pyiron_atomistics =0.3.4
- pyiron_base =0.6.8
- pyiron-data =0.0.24
- python-graphviz =0.20.1
- toposort =1.10
- typeguard =4.1.5
